### ISSUE TITLE
Manifest merger failed 

### ISSUE THREAD

**Issue by rchincho** [fiskurgit/SimpleViewPager#1]
Error:Execution failed for task ':workm:processDebugManifest'.
> Manifest merger failed : Attribute application@icon value=(@drawable/ic_launcher) from AndroidManifest.xml:53:9-45
  	is also present at [com.github.fiskurgit:SimpleViewPager:1.0.2] AndroidManifest.xml:13:9-43 value=(@mipmap/ic_launcher).
  	Suggestion: add 'tools:replace="android:icon"' to <application> element at AndroidManifest.xml:50:5-243:19 to override.

**Comment by fiskurgit** [comment]
Sorry for the delay - I missed this first time around. Fixed in 1.0.4

**Comment by kevinwo** [comment]
This appears to still be an issue.  I'm getting a collision with "android:label":

> Error:Execution failed for task ':app:processDebugManifest'.
> > Manifest merger failed : Attribute application@label value=(@string/short_app_name) from AndroidManifest.xml:9:9-47
>   	is also present at [com.github.fiskurgit:SimpleViewPager:1.0.5] AndroidManifest.xml:13:9-41 value=(@string/app_name).
>   	Suggestion: add 'tools:replace="android:label"' to <application> element at AndroidManifest.xml:5:5-34:19 to override.

**Comment by fiskurgit** [comment]
k, will have a look, should have a fix up sometime in the next few hours.

**Comment by fiskurgit** [comment]
Okay, try 1.0.6
