### ISSUE TITLE
Scale type , Circle padding bottom not working XML

### ISSUE THREAD

**Issue by davin12x** [fiskurgit/SimpleViewPager#6]
Hi , when i' m using scale type through XML . I got compile time error that no resource found for attribute scale type.

**Comment by fiskurgit** [comment]
Will look into after the weekend - thanks.

**Comment by TGIO** [comment]
[cause](https://github.com/fiskurgit/SimpleViewPager/blob/362f38f560e5a90f11e9ef2f733d493636344ba5/library/src/main/java/eu/fiskur/simpleviewpager/SimpleViewPager.java#L147)

**Comment by fiskurgit** [comment]
Apologies I'm well over a year late with this response, but you need to use the app/liob name space for that attribute, not the android one: `xmlns:simpleviewpager="http://schemas.android.com/apk/res-auto`

`simpleviewpager:scaleType="CENTER_CROP"`

I suspect that's the problem.
