### ISSUE TITLE
Attribute "scaleType" already defined with incompatible format

### ISSUE THREAD

**Issue by alaaghribi** [fiskurgit/SimpleViewPager#7]
Hi,
When trying to install the library, the gradle building stops with errors :

> ...\app\build\intermediates\res\merged\debug\values\values.xml
> Error:(391) Attribute "scaleType" already defined with incompatible format.

Any solution?

Thanks .

**Comment by fiskurgit** [comment]
Sorry for the delay, well over a year... I'm unable to replicate this.
