### ISSUE TITLE
Crashes when I remove pager.showIndicator();

### ISSUE THREAD

**Issue by lpraneeth** [fiskurgit/SimpleViewPager#8]
I dont want those dotes appear on the images in my view pager! I dint find any way put them bellow the image! so, when I try to remove this line:
mViewPager.showIndicator(indicatorColor, selectedIndicatorColor);

My app crashes when I open the page throwing null pointer exception! pls help me!

here is the crash:
 'android.view.View android.widget.LinearLayout.getChildAt(int)' on a null object reference

**Comment by fiskurgit** [comment]
Over a year late - apologies, but this should be fixed in 1.0.11.
